#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Jun 28 18:57:02 GMT-03:00 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=12
shaderPack=Mellow Shader v3.2.zip
