# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"
# The chunk rebuild scheduler mode (immediate, culling).
chunk_rebuild_scheduler = "culling"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enables dynamic lighting of beacon or end gateway beams.
	beam = true
	# Enables dynamic lighting of firefly particles from Firefly Bushes.
	firefly = true
	# Enables dynamic lighting for entities that have the Glowing effect.
	glowing_effect = true
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Enables dynamic lighting of the Warden's sonic boom attack particles.
	sonic_boom = true
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"
	# Enables dynamic lighting of Guardian's lasers. This also can be toggled off by disabling Guardian dynamic lighting.
	guardian_laser = true

			[light_sources.settings.entities.minecraft]
				pale_oak_boat = false
				zombie_horse = false
				axolotl = false
				egg = false
				zoglin = false
				spawner_minecart = false
				allay = false
				jungle_chest_boat = false
				llama = false
				mule = false
				bat = false
				husk = false
				camel = false
				experience_bottle = false
				rabbit = false
				firework_rocket = false
				silverfish = false
				happy_ghast = false
				giant = false
				drowned = false
				creaking = false
				item = false
				oak_chest_boat = false
				goat = false
				horse = false
				vindicator = false
				birch_boat = false
				minecart = false
				spectral_arrow = false
				oak_boat = false
				llama_spit = false
				mooshroom = false
				glow_item_frame = false
				snowball = false
				tnt = true
				parrot = false
				creeper = false
				lightning_bolt = true
				tadpole = false
				ravager = false
				evoker_fangs = false
				chest_minecart = false
				tropical_fish = false
				slime = false
				parched = false
				pillager = false
				dark_oak_chest_boat = false
				area_effect_cloud = false
				blaze = false
				piglin = false
				end_crystal = false
				endermite = false
				zombie = false
				ender_pearl = false
				item_display = false
				breeze_wind_charge = false
				guardian = false
				fireball = false
				illusioner = false
				wither_skull = false
				eye_of_ender = false
				wolf = false
				zombie_nautilus = false
				zombie_villager = false
				tnt_minecart = false
				block_display = false
				elder_guardian = false
				cherry_chest_boat = false
				acacia_chest_boat = false
				small_fireball = false
				strider = false
				cave_spider = false
				cod = false
				witch = false
				snow_golem = false
				spider = false
				command_block_minecart = false
				panda = false
				bee = false
				arrow = false
				mannequin = false
				lingering_potion = false
				cow = false
				birch_chest_boat = false
				magma_cube = false
				pig = false
				skeleton = false
				spruce_boat = false
				frog = false
				hoglin = false
				armadillo = false
				splash_potion = false
				armor_stand = false
				experience_orb = false
				dolphin = false
				stray = false
				jungle_boat = false
				shulker = false
				turtle = false
				wither_skeleton = false
				salmon = false
				wandering_trader = false
				vex = false
				piglin_brute = false
				nautilus = false
				breeze = false
				ocelot = false
				acacia_boat = false
				pale_oak_chest_boat = false
				furnace_minecart = false
				mangrove_boat = false
				item_frame = false
				phantom = false
				ender_dragon = false
				leash_knot = false
				evoker = false
				marker = true
				glow_squid = false
				warden = false
				squid = false
				shulker_bullet = false
				enderman = false
				dragon_fireball = false
				copper_golem = false
				chicken = false
				sniffer = false
				dark_oak_boat = false
				trader_llama = false
				donkey = false
				bamboo_chest_raft = false
				bogged = false
				bamboo_raft = false
				fox = false
				mangrove_chest_boat = false
				camel_husk = false
				cherry_boat = false
				iron_golem = false
				zombified_piglin = false
				cat = false
				wind_charge = false
				ghast = false
				sheep = false
				player = true
				pufferfish = false
				trident = false
				villager = false
				skeleton_horse = false
				ominous_item_spawner = false
				fishing_bobber = false
				text_display = false
				polar_bear = false
				hopper_minecart = false
				falling_block = false
				painting = false
				interaction = false
				wither = false
				spruce_chest_boat = false

[debug]
	active_dynamic_lighting_cells = false
	display_dynamic_lighting_chunk_rebuild = false
	display_behavior_bounding_box = false

[adaptive_ticking]
	# Reduces how often sources behind the camera get ticked.
	background_sleep = true
	# How far away (in chunks) until light sources get ticked less often.
	slow = 5
	# How far away (in chunks) until light sources get ticked even less often.
	slower = 8
