version = 1
enableSodiumMenu = true
dontCull = []
cloudCulling = true
signTextCulling = true
rainCulling = true
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 6
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 4.0
paintingCulling = true
leavesCullingMode = "FAST"
leavesCullingAmount = 3
includeMangroveRoots = true
endGatewayCulling = true
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
easymagic = true
easyanvils = true
visualworkbench = true
minecraft = true
